KDTREE_DIST_UPPERBOUND = 500 # Maximum distance for KDTree search
d_box= 500 # defines BOX around central point to filter data (urb and flam) and create plots 
K = 40 # Number of flammable neighbors to explore
KF =40 # Number of urban neighbors of the flammable neighbors to explore 
limiar = 1.05 # Threshold for triangular inequality
limiartheta = 60  # Largest angle to be eligible to protect
QT = 5 # minimum contribution of one side to the triangle perimeter (%)
KS = list(range(1, K + 1)) # Flammable neighbors range
KFS = list(range(1, KF + 1))  # Urban neighbors range
MAXDIST = 0  # If 0 do not densify #to densify: maximum distance in meters between urban vertices
tolerance = 3 # Distance tolerance
bigN = 10**6  # large number (larger than 3763 coordinates over Portugal)
smallN = 10**-6 # small number
POSVALUE = 9999 # Large positive value 
NEGVALUE = -1  # NA value for variables that can only be positive (distance, azimuth, feature index)
ADDVAR = False  # To use an additional urban attribute in the construction of interface elements (e.g., district)
NEWVAR = "fid_1"  # Replace with, e.g., "district" (or whatever the name of the urban attribute to consider)
ADDVAR2 = False  # Use a second additional urban attribute
NEWVAR2 = "CorePC" # Second attribute name
ADDFLAMVAR = False # Include additional flammable attribute in output
NEWFLAMVAR = "idflam"   # Flammable feature ID (auto-generated) added to the output
ADDFLAMVAR2 = False  # Include second flammable attribute added to the output
NEWFLAMVAR2 = "FuelRisk" # Second flammable attribute name to the output
